# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site title and description
title:              Micromata Weihnachten 2021
description:        Ein Weihnachtsgruß von Micromata
lang:               de

# Site subpath, e.g. /blog
baseurl:            ""

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink:          /:title/

# Site base hostname & protocol, e.g. http://example.com
url:                ""

# Site logo # e.g. logo.png, upload logo image file to /uploads/ folder
logo:               signet-micromata.svg

navbar:
  sticky:         true
  search:         false

# Default author settings
author:
  name:           Micromata GmbH
  title:          Micromata GmbH
  avatar:

# Team settings
teams:
  GL:
    name:         GL
    # This has to be the name of the /uploads subfolder as well as the playlist and TS files!
    # My recommendation: just name the video and folder after the team.
    video:        test1
  merck:
    name:         Merck
    video:        test1
  dhl-vls:
    name:         DHL VLS
    video:        test1
  viessmann:
    name:         Viessmann
    video:        test1
  porsche-dpp:
    name:         Porsche DPP
    video:        test1
  dhl-nolp:
    name:         DHL NOLP
    video:        test1
  vw-werbung:
    name:         Porsche DPP
    video:        test1
  porsche-iris:
    name:         Porsche IRIS
    video:        test1
  polyas:
    name:         POLYAS
    video:        test1
  wingas:
    name:         WINGAS
    video:        test1
  vw-pricing:
    name:         VW Pricing
    video:        test1
  dhl-pka:
    name:         DHL PKA
    video:        test1
  dhl-of:
    name:         DHL OF
    video:        test1

# Social icons displayed in footer
social:
  email:
  website:        https://micromata.de
  facebook:       https://www.facebook.com/
  instagram:      https://www.instagram.com/micromata/
  twitter:        https://twitter.com/micromata
  vimeo:          https://vimeo.com/user44553474
  youtube:

# Default footer image settings
footer:
  copyright:      <a href="https://micromata.de/">&copy; Micromata GmbH</a>

# Disqus comments shortname, requires Disqus account https://disqus.com/
disqus:
  shortname:      # 1234

# Google analytics code, get your code here https://www.google.com/analytics/
#google_analytics:

# Number of posts displayed on blog page
# paginate:           10

# Blog path
# paginate_path:      "/blog/:num/"

# Path to post content assets directory i.e post images, pdfs etc
uploads:            /uploads/

# Build settings
markdown:           kramdown
highlighter:        rouge

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .idea
  - README.md
  - convert-video.sh
include:
  - /node_modules/video.js/dist/video-js.min.css
  - /node_modules/video.js/dist/video.min.js
  - /node_modules/videojs-contrib-dash/dist/videojs-dash.min.js
  - /node_modules/dashjs/dist/dash.all.min.js.map
  - /node_modules/dashjs/dist/dash.all.min.js
  - /node_modules/uikit/dist/js/uikit.min.js
  - /node_modules/uikit/dist/js/uikit-icons.min.js

sass:
  style:            compressed

collections:
  docs:
    output:         true
  faqs:
    output:         false
  changelogs:
    output:         false

# Defaults
defaults:
  # _posts
  - scope:
      path:         ""
      type:         posts
    values:
      layout:       post
  # _docs
  - scope:
      path:         ""
      type:         docs
    values:
      layout:       doc
